### ISSUE TITLE
Conversations Deleted Immediately on Three-Dot Click in Sidebar

### ISSUE THREAD

**Issue by amritav** [NCSUTAChatBot/llm-chatbot#45]
Description:
Clicking the three dots (...) next to a conversation in the sidebar immediately deletes the conversation without any confirmation or additional options.

	•	When a user clicks on the three dots (...) next to a conversation in the sidebar, a dropdown menu should appear.
	•	The dropdown menu should contain the following options:
	1.	Rename: Allows the user to rename the conversation.
	2.	Delete: Allows the user to delete the conversation. Ideally, this should include a confirmation step (e.g., “Are you sure you want to delete this conversation?”).

**Comment by sanjitkverma** [comment]
solved with #68
