### ISSUE TITLE
Chatbot Stream Response Issue

### ISSUE THREAD

**Issue by sanjitkverma** [NCSUTAChatBot/llm-chatbot#54]
(potentially backends not responding) A few times the prompt just does not return anything.
![image](https://github.com/user-attachments/assets/6901580d-1fd9-49e0-927c-f8f0fd4a94ea)

**Comment by sanjitkverma** [comment]
At first glance, the beta user reported that the chatbot is not responding. I believe this is no the issue, the chatbot can be slow sometimes and takes longer to respond. However, that being said, the user should not be able to type another prompt in while the chatbot hasn't responded to the first one. 

Please take a look at both of these issues and confirm if the issue truly is the chatbot is not responding or not.

**Comment by deep41** [comment]
The latency issue with small or bigger answers was fixed in one of my commits. 
Worth investigating if this issue still persists. But I do believe it's fixes.

Closing issue
