### ISSUE TITLE
In-chat context does not seem to work as expected

### ISSUE THREAD

**Issue by sanjitkverma** [NCSUTAChatBot/llm-chatbot#64]
Chat history context doesn't work as expected, see below:

![Screenshot 2024-09-23 at 5 09 13 PM](https://github.com/user-attachments/assets/9ebf15ff-b421-4a54-b6ac-3e4799887c37)

Needs some investigation, not sure whats occurring here

**Comment by deep41** [comment]
I check langfuse if the history was passed correctly and it was.
I was able to get it working by removing the below from the prompt template.

```sh
If asked a question not in the context, do not answer it and say I'm sorry, I do not know the answer to that question.
If you don't know the answer or if it is not provided in the context, just say that you don't know, don't try to make up an answer.
If asked a question not in the context, do not answer it and say I'm sorry, I do not know the answer to that question.
If the answer is in the context, don't say mentioned in the context.
```

![Image](https://github.com/user-attachments/assets/2397408d-4733-4c9a-a97d-ef025fc3c9fe)

**Comment by deep41** [comment]
I think I'll have to explore ideas from the prompt engineering perspective rather than coding for this.
