### ISSUE TITLE
Course Evaluation Chatbot file Upload Issue

### ISSUE THREAD

**Issue by sanjitkverma** [NCSUTAChatBot/llm-chatbot#82]
Users can prompt the chatbot before the file is uploaded which causes an error sometimes or a bad response from the chatbot and makes the chatbot be stuck on responses sometimes. This should not be. The chatbot input field should be grayed out until the file is completed uploading

<img width="1706" alt="Screenshot 2024-10-22 at 2 53 11 PM" src="https://github.com/user-attachments/assets/acb5d39c-623c-4581-8821-db5bd8f0caea">

It should remain like this until file bar is done uploading:

<img width="1225" alt="Screenshot 2024-10-22 at 2 54 15 PM" src="https://github.com/user-attachments/assets/89fb7bf5-ff5f-4cea-b428-f53c30a026a7">

**Comment by dineshkannan010** [comment]
Updated code such that  until the whole file is uploaded the bot will not allow the user to type the prompt.
